version: '3.9'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: attendance_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    environment:
      - PORT=4000
      - JWT_SECRET=change_me
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=attendance_db
      - HR_EMAIL=concur.dev@gmail.com
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    image: node:22-alpine
    working_dir: /app
    command: sh -c "yarn && yarn dev --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000/api
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  mysql_data: